services:
  postgres:
    image: postgres:16-alpine
    container_name: astranodes_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: astranodes
      POSTGRES_USER: astranodes
      POSTGRES_PASSWORD: changeme
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: astranodes_redis
    restart: unless-stopped
    ports:
      - '6380:6379'
    command: redis-server --save 60 1 --loglevel warning

volumes:
  postgres_data:
