import dotenv from "dotenv"
import path from "path"
import { fileURLToPath } from "url"
import Database from "better-sqlite3"
import pg from "pg"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
dotenv.config({ path: path.join(__dirname, "../.env"), override: true })

const { Pool } = pg

const SQLITE_PATH = process.env.DB_PATH || "./data/astranodes.sqlite"
const DATABASE_URL = process.env.DATABASE_URL
const DB_PROVIDER = process.env.DB_PROVIDER || "sqlite"
const DB_SSL = process.env.DB_SSL === "true"

if (DB_PROVIDER !== "postgres") {
  console.error("[MIGRATE PG] DB_PROVIDER must be 'postgres' to run this migration")
  process.exit(1)
}

if (!DATABASE_URL) {
  console.error("[MIGRATE PG] DATABASE_URL is required")
  process.exit(1)
}

const orderedTables = [
  "users",
  "plans_coin",
  "plans_real",
  "servers",
  "coin_settings",
  "coupons",
  "coupon_redemptions",
  "utr_submissions",
  "site_content",
  "landing_plans",
  "site_settings",
  "plans",
  "features",
  "vouchers",
  "announcements",
  "tickets",
  "ticket_messages",
  "server_backups",
  "audit_log",
  "idempotency_keys"
]

const serialTables = [
  "users",
  "plans_coin",
  "plans_real",
  "servers",
  "coupons",
  "coupon_redemptions",
  "utr_submissions",
  "site_content",
  "landing_plans",
  "site_settings",
  "plans",
  "features",
  "vouchers",
  "announcements",
  "tickets",
  "ticket_messages",
  "server_backups",
  "audit_log",
  "idempotency_keys"
]

const schemaSql = `
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT,
  role TEXT NOT NULL DEFAULT 'user',
  coins BIGINT NOT NULL DEFAULT 0,
  balance DOUBLE PRECISION NOT NULL DEFAULT 0,
  ip_address TEXT,
  last_login_ip TEXT,
  pterodactyl_user_id BIGINT,
  flagged INTEGER NOT NULL DEFAULT 0,
  last_claim_time TEXT,
  oauth_provider TEXT,
  oauth_id TEXT,
  email_verified INTEGER NOT NULL DEFAULT 0,
  verification_token TEXT,
  verification_token_expires TEXT,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS plans_coin (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  icon TEXT,
  category TEXT NOT NULL,
  ram DOUBLE PRECISION NOT NULL,
  cpu DOUBLE PRECISION NOT NULL,
  storage DOUBLE PRECISION NOT NULL,
  coin_price BIGINT NOT NULL,
  initial_price BIGINT NOT NULL,
  renewal_price BIGINT NOT NULL,
  duration_type TEXT NOT NULL,
  duration_days BIGINT NOT NULL,
  limited_stock INTEGER NOT NULL,
  stock_amount BIGINT,
  one_time_purchase INTEGER NOT NULL,
  backup_count BIGINT NOT NULL,
  extra_ports BIGINT NOT NULL,
  swap BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS plans_real (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  icon TEXT,
  category TEXT NOT NULL,
  ram DOUBLE PRECISION NOT NULL,
  cpu DOUBLE PRECISION NOT NULL,
  storage DOUBLE PRECISION NOT NULL,
  price DOUBLE PRECISION NOT NULL,
  duration_type TEXT NOT NULL,
  duration_days BIGINT NOT NULL,
  limited_stock INTEGER NOT NULL,
  stock_amount BIGINT,
  backup_count BIGINT NOT NULL,
  extra_ports BIGINT NOT NULL,
  swap BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS servers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  plan_type TEXT NOT NULL,
  plan_id BIGINT NOT NULL,
  pterodactyl_server_id BIGINT,
  identifier TEXT,
  expires_at TEXT NOT NULL,
  suspended_at TEXT,
  grace_expires_at TEXT,
  status TEXT NOT NULL,
  location TEXT NOT NULL,
  software TEXT NOT NULL,
  category TEXT NOT NULL,
  egg_id BIGINT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS coin_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coins_per_minute BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS coupons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  coin_reward BIGINT NOT NULL,
  max_uses BIGINT NOT NULL,
  per_user_limit BIGINT NOT NULL,
  expires_at TEXT NOT NULL,
  active INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS coupon_redemptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coupon_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  ip_address TEXT NOT NULL,
  redeemed_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS utr_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  amount DOUBLE PRECISION NOT NULL,
  utr_number TEXT NOT NULL,
  screenshot_path TEXT NOT NULL,
  status TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS site_content (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section_name TEXT NOT NULL UNIQUE,
  content_json TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS landing_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price DOUBLE PRECISION NOT NULL,
  ram BIGINT NOT NULL,
  cpu BIGINT NOT NULL,
  storage BIGINT NOT NULL,
  features TEXT NOT NULL,
  popular INTEGER NOT NULL,
  active INTEGER NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS site_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_name TEXT,
  background_image TEXT,
  background_overlay_opacity DOUBLE PRECISION,
  favicon_path TEXT,
  logo_path TEXT,
  hero_title TEXT,
  hero_subtitle TEXT,
  maintenance_mode INTEGER
);

CREATE TABLE IF NOT EXISTS plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  ram BIGINT,
  cpu BIGINT,
  storage BIGINT,
  price DOUBLE PRECISION,
  description TEXT,
  is_active INTEGER
);

CREATE TABLE IF NOT EXISTS features (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT,
  description TEXT,
  icon TEXT
);

CREATE TABLE IF NOT EXISTS vouchers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT,
  coins BIGINT,
  expires_at TEXT,
  is_active INTEGER
);

CREATE TABLE IF NOT EXISTS announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message TEXT,
  is_active INTEGER
);

CREATE TABLE IF NOT EXISTS tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  category TEXT NOT NULL,
  subject TEXT NOT NULL,
  status TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  priority TEXT,
  username TEXT,
  email TEXT
);

CREATE TABLE IF NOT EXISTS ticket_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id BIGINT NOT NULL,
  sender_type TEXT NOT NULL,
  sender_id BIGINT NOT NULL,
  message TEXT NOT NULL,
  created_at TEXT NOT NULL,
  image TEXT
);

CREATE TABLE IF NOT EXISTS server_backups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  server_id BIGINT NOT NULL,
  pterodactyl_backup_uuid TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  is_automatic INTEGER NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id BIGINT NOT NULL,
  action TEXT NOT NULL,
  target_type TEXT,
  target_id BIGINT,
  details TEXT,
  ip_address TEXT,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS idempotency_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  endpoint TEXT NOT NULL,
  key TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'processing',
  status_code BIGINT,
  response_json TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (user_id, endpoint, key)
);
`

function quoteIdentifier(name) {
  return `"${name.replaceAll('"', '""')}"`
}

function sqliteTableExists(sqliteDb, tableName) {
  const row = sqliteDb
    .prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name = ?")
    .get(tableName)
  return Boolean(row)
}

async function copyTable(sqliteDb, client, tableName) {
  if (!sqliteTableExists(sqliteDb, tableName)) {
    console.log(`[MIGRATE PG] Source table missing in SQLite, skipping: ${tableName}`)
    return
  }

  const rows = sqliteDb.prepare(`SELECT * FROM ${tableName}`).all()
  if (!rows.length) return

  const columns = Object.keys(rows[0])
  const colList = columns.map(quoteIdentifier).join(", ")

  for (const row of rows) {
    const values = columns.map((c) => row[c])
    const placeholders = values.map((_, i) => `$${i + 1}`).join(", ")
    await client.query(
      `INSERT INTO ${quoteIdentifier(tableName)} (${colList}) VALUES (${placeholders})`,
      values
    )
  }
}

async function main() {
  const sqliteDb = new Database(SQLITE_PATH, { readonly: true })
  const pool = new Pool({
    connectionString: DATABASE_URL,
    ssl: DB_SSL ? { rejectUnauthorized: false } : false,
    max: 10
  })

  const client = await pool.connect()
  try {
    console.log("[MIGRATE PG] Preparing PostgreSQL schema...")
    await client.query("BEGIN")
    await client.query(schemaSql)

    for (const table of orderedTables) {
      await client.query(`TRUNCATE TABLE ${quoteIdentifier(table)} RESTART IDENTITY CASCADE`)
    }

    console.log("[MIGRATE PG] Copying data from SQLite...")
    for (const table of orderedTables) {
      await copyTable(sqliteDb, client, table)
      console.log(`[MIGRATE PG] ✓ ${table}`)
    }

    for (const table of serialTables) {
      await client.query(
        `SELECT setval(pg_get_serial_sequence('${table}', 'id'), COALESCE((SELECT MAX(id) FROM ${quoteIdentifier(table)}), 1), true)`
      ).catch(() => {})
    }

    await client.query("COMMIT")
    console.log("[MIGRATE PG] Migration completed successfully")
  } catch (error) {
    await client.query("ROLLBACK").catch(() => {})
    console.error("[MIGRATE PG] Failed:", error.message)
    process.exitCode = 1
  } finally {
    sqliteDb.close()
    client.release()
    await pool.end()
  }
}

main().catch((error) => {
  console.error("[MIGRATE PG] Error:", error.message)
  process.exit(1)
})
