CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  password_hash TEXT,
  role TEXT NOT NULL DEFAULT 'user',
  coins BIGINT NOT NULL DEFAULT 0,
  balance DOUBLE PRECISION NOT NULL DEFAULT 0,
  ip_address TEXT,
  last_login_ip TEXT,
  pterodactyl_user_id BIGINT,
  flagged INTEGER NOT NULL DEFAULT 0,
  last_claim_time TEXT,
  oauth_provider TEXT,
  oauth_id TEXT,
  email_verified INTEGER NOT NULL DEFAULT 0,
  verification_token TEXT,
  verification_token_expires TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS plans_coin (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  icon TEXT,
  category TEXT NOT NULL DEFAULT 'minecraft',
  ram DOUBLE PRECISION NOT NULL,
  cpu DOUBLE PRECISION NOT NULL,
  storage DOUBLE PRECISION NOT NULL,
  coin_price BIGINT NOT NULL,
  initial_price BIGINT NOT NULL DEFAULT 0,
  renewal_price BIGINT NOT NULL DEFAULT 0,
  duration_type TEXT NOT NULL,
  duration_days BIGINT NOT NULL,
  limited_stock INTEGER NOT NULL DEFAULT 0,
  stock_amount BIGINT,
  one_time_purchase INTEGER NOT NULL DEFAULT 0,
  backup_count BIGINT NOT NULL DEFAULT 0,
  extra_ports BIGINT NOT NULL DEFAULT 0,
  swap BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS plans_real (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  icon TEXT,
  category TEXT NOT NULL DEFAULT 'minecraft',
  ram DOUBLE PRECISION NOT NULL,
  cpu DOUBLE PRECISION NOT NULL,
  storage DOUBLE PRECISION NOT NULL,
  price DOUBLE PRECISION NOT NULL,
  duration_type TEXT NOT NULL,
  duration_days BIGINT NOT NULL,
  limited_stock INTEGER NOT NULL DEFAULT 0,
  stock_amount BIGINT,
  backup_count BIGINT NOT NULL DEFAULT 0,
  extra_ports BIGINT NOT NULL DEFAULT 0,
  swap BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS servers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  name TEXT NOT NULL DEFAULT '',
  plan_type TEXT NOT NULL,
  plan_id BIGINT NOT NULL,
  pterodactyl_server_id BIGINT,
  identifier TEXT,
  expires_at TEXT NOT NULL,
  suspended_at TEXT,
  grace_expires_at TEXT,
  status TEXT NOT NULL,
  location TEXT NOT NULL DEFAULT '',
  software TEXT NOT NULL DEFAULT 'minecraft',
  category TEXT NOT NULL DEFAULT 'minecraft',
  egg_id BIGINT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS coin_settings (
  id BIGINT PRIMARY KEY,
  coins_per_minute BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS coupons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  coin_reward BIGINT NOT NULL,
  max_uses BIGINT NOT NULL,
  per_user_limit BIGINT NOT NULL,
  expires_at TEXT NOT NULL,
  active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS coupon_redemptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coupon_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  ip_address TEXT NOT NULL,
  redeemed_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (coupon_id) REFERENCES coupons(id),
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS utr_submissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  amount DOUBLE PRECISION NOT NULL,
  utr_number TEXT NOT NULL,
  screenshot_path TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS site_content (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section_name TEXT NOT NULL UNIQUE,
  content_json TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS landing_plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  price DOUBLE PRECISION NOT NULL,
  ram BIGINT NOT NULL,
  cpu BIGINT NOT NULL,
  storage BIGINT NOT NULL,
  features TEXT NOT NULL,
  popular INTEGER NOT NULL DEFAULT 0,
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS site_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_name TEXT,
  background_image TEXT,
  background_overlay_opacity DOUBLE PRECISION,
  favicon_path TEXT,
  logo_path TEXT,
  hero_title TEXT,
  hero_subtitle TEXT,
  maintenance_mode INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS plans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT,
  ram BIGINT,
  cpu BIGINT,
  storage BIGINT,
  price DOUBLE PRECISION,
  description TEXT,
  is_active INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS features (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT,
  description TEXT,
  icon TEXT
);

CREATE TABLE IF NOT EXISTS vouchers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT,
  coins BIGINT,
  expires_at TEXT,
  is_active INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message TEXT,
  is_active INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  category TEXT NOT NULL,
  subject TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open',
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  priority TEXT DEFAULT 'Medium',
  username TEXT,
  email TEXT,
  FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS ticket_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id BIGINT NOT NULL,
  sender_type TEXT NOT NULL,
  sender_id BIGINT NOT NULL,
  message TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  image TEXT,
  FOREIGN KEY (ticket_id) REFERENCES tickets(id)
);

CREATE TABLE IF NOT EXISTS server_backups (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  server_id BIGINT NOT NULL,
  pterodactyl_backup_uuid TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL DEFAULT 'backup',
  is_automatic INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (server_id) REFERENCES servers(id)
);

CREATE TABLE IF NOT EXISTS audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id BIGINT NOT NULL,
  action TEXT NOT NULL,
  target_type TEXT,
  target_id BIGINT,
  details TEXT,
  ip_address TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (admin_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS idempotency_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  endpoint TEXT NOT NULL,
  key TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'processing',
  status_code BIGINT,
  response_json TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id),
  UNIQUE (user_id, endpoint, key)
);

CREATE INDEX IF NOT EXISTS idx_servers_user ON servers(user_id);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_users_oauth ON users(oauth_provider, oauth_id);
CREATE INDEX IF NOT EXISTS idx_coupon_redemptions_user ON coupon_redemptions(user_id);
CREATE INDEX IF NOT EXISTS idx_utr_submissions_user ON utr_submissions(user_id);
CREATE INDEX IF NOT EXISTS idx_utr_submissions_status ON utr_submissions(status);
CREATE INDEX IF NOT EXISTS idx_tickets_priority ON tickets(priority);
CREATE INDEX IF NOT EXISTS idx_server_backups_server ON server_backups(server_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_admin ON audit_log(admin_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_created ON audit_log(created_at);
CREATE INDEX IF NOT EXISTS idx_idempotency_lookup ON idempotency_keys(user_id, endpoint, key);

INSERT INTO coin_settings (id, coins_per_minute)
VALUES (1, 1)
ON CONFLICT (id) DO NOTHING;
